Sub main()
    Dim swApp As SldWorks.SldWorks
    Set swApp = Application.SldWorks
    
    If swApp Is Nothing Then
        MsgBox "Cannot connect to SolidWorks"
        Exit Sub
    End If
    
    MsgBox "Creating a new part"
    
    Dim swModel As SldWorks.ModelDoc2
    Set swModel = swApp.NewDocument("C:\ProgramData\SOLIDWORKS\SOLIDWORKS 2022\templates\Part.prtdot", 0, 0, 0)
    
    If swModel Is Nothing Then
        MsgBox "Failed to create new part"
        Exit Sub
    End If
    
    MsgBox "New part created successfully"
End Sub

Sub CreateSketch()
    Dim swApp As SldWorks.SldWorks
    Set swApp = Application.SldWorks
    
    Dim swModel As SldWorks.ModelDoc2
    Set swModel = swApp.ActiveDoc
    
    If swModel Is Nothing Then
        MsgBox "No active document"
        Exit Sub
    End If
    
    MsgBox "Creating sketch on Front plane"
    
    Dim boolstatus As Boolean
    boolstatus = swModel.Extension.SelectByID2("Front Plane", "PLANE", 0, 0, 0, False, 0, Nothing, 0)
    swModel.SketchManager.InsertSketch True
    
    MsgBox "Sketch created"
End Sub