{
  "MacroPaths": [
    "D:\\codebase\\MecAgent Folder\\MecAgent-GPT-B\\MiniSw\\bin\\Release\\net8.0-windows\\My SW Macros",
    "E:\\this-macros\\SW Macro\\CS",
    "E:\\this-macros\\SW Macro\\SWP"
  ],
  "Prompts": [
    {
      "Id": "813a194f-2f83-409d-a3f2-5e883daa9864",
      "Name": "C# SolidWorks \u5B8F\u751F\u6210",
      "Content": "\u8ACB\u5E6B\u6211\u751F\u6210 SolidWorks C# \u5B8F\u4EE3\u78BC\u3002\n\n\u3010\u57F7\u884C\u74B0\u5883\u8AAA\u660E\u3011\n- \u9019\u662F\u4E00\u500B C# \u8173\u672C\u74B0\u5883\uFF0C\u4E0D\u9700\u8981 class \u5305\u88DD\n- \u5DF2\u6709\u8B8A\u91CF: swApp (ISldWorks), swModel (IModelDoc2)\n- \u5DF2\u5C0E\u5165\u547D\u540D\u7A7A\u9593: System, System.IO, System.Linq, System.Collections.Generic\n- \u5DF2\u5C0E\u5165\u547D\u540D\u7A7A\u9593: SolidWorks.Interop.sldworks, SolidWorks.Interop.swconst\n- \u8F38\u51FA\u51FD\u6578: Print(msg), PrintError(msg), PrintWarning(msg)\n\n\u3010\u4EE3\u78BC\u8981\u6C42\u3011\n1. \u76F4\u63A5\u5BEB\u8173\u672C\u4EE3\u78BC\uFF0C\u4E0D\u9700\u8981 class \u6216 namespace\n2. \u4F7F\u7528 Print() \u8F38\u51FA\u4FE1\u606F\uFF0C\u4E0D\u8981\u7528 Console.WriteLine\n3. \u6DFB\u52A0\u7A7A\u503C\u6AA2\u67E5\u548C\u932F\u8AA4\u8655\u7406\n4. \u6DFB\u52A0\u4E2D\u6587\u8A3B\u91CB\u8AAA\u660E\u4EE3\u78BC\u529F\u80FD\n\n\u3010\u5E38\u7528 API \u7BC4\u4F8B\u3011\n\n// \u7372\u53D6\u6D3B\u52D5\u6587\u6A94\nif (swModel == null) { PrintError(\u0022\u8ACB\u5148\u6253\u958B\u6587\u6A94\u0022); return; }\n\n// \u5224\u65B7\u6587\u6A94\u985E\u578B\nint docType = swModel.GetType();\nif (docType == (int)swDocumentTypes_e.swDocPART) { Print(\u0022\u9019\u662F\u96F6\u4EF6\u0022); }\nif (docType == (int)swDocumentTypes_e.swDocASSEMBLY) { Print(\u0022\u9019\u662F\u88DD\u914D\u9AD4\u0022); }\nif (docType == (int)swDocumentTypes_e.swDocDRAWING) { Print(\u0022\u9019\u662F\u5DE5\u7A0B\u5716\u0022); }\n\n// \u7372\u53D6\u6587\u6A94\u8DEF\u5F91\nstring path = swModel.GetPathName();\nstring dir = Path.GetDirectoryName(path);\nstring name = Path.GetFileNameWithoutExtension(path);\n\n// \u904D\u6B77\u96F6\u4EF6\u4E2D\u7684\u6240\u6709\u5BE6\u9AD4\nIPartDoc swPart = swModel as IPartDoc;\nobject[] bodies = swPart.GetBodies2((int)swBodyType_e.swSolidBody, true) as object[];\n\n// \u904D\u6B77\u88DD\u914D\u9AD4\u4E2D\u7684\u7D44\u4EF6\nIAssemblyDoc swAssy = swModel as IAssemblyDoc;\nobject[] comps = swAssy.GetComponents(true) as object[];\nforeach (IComponent2 comp in comps) { Print(comp.Name2); }\n\n// \u9078\u64C7\u7BA1\u7406\u5668\nISelectionMgr selMgr = swModel.ISelectionManager;\nint count = selMgr.GetSelectedObjectCount2(-1);\n\n// \u81EA\u5B9A\u7FA9\u5C6C\u6027\nIModelDocExtension ext = swModel.Extension;\nICustomPropertyManager propMgr = ext.get_CustomPropertyManager(\u0022\u0022);\npropMgr.Add3(\u0022\u5C6C\u6027\u540D\u0022, (int)swCustomInfoType_e.swCustomInfoText, \u0022\u503C\u0022, 0);\n\n// \u4FDD\u5B58\u6587\u6A94\nswModel.Save3((int)swSaveAsOptions_e.swSaveAsOptions_Silent, ref errors, ref warnings);\n\n\u3010\u529F\u80FD\u9700\u6C42\u3011\n[\u5728\u6B64\u63CF\u8FF0\u4F60\u9700\u8981\u7684\u529F\u80FD]",
      "IsDefault": true
    },
    {
      "Id": "647e38a1-2261-4f99-854d-33e307fe1a53",
      "Name": "VBA SolidWorks \u5B8F\u751F\u6210",
      "Content": "\u8ACB\u5E6B\u6211\u751F\u6210 SolidWorks VBA \u5B8F\u4EE3\u78BC\u3002\n\n\u3010\u4EE3\u78BC\u8981\u6C42\u3011\n1. \u4F7F\u7528\u6A19\u6E96 VBA \u8A9E\u6CD5\n2. \u5305\u542B Sub main() \u4F5C\u70BA\u5165\u53E3\u9EDE\n3. \u6DFB\u52A0\u9069\u7576\u7684\u932F\u8AA4\u8655\u7406 (On Error GoTo)\n4. \u6DFB\u52A0\u4E2D\u6587\u8A3B\u91CB\u8AAA\u660E\u4EE3\u78BC\u529F\u80FD\n\n\u3010\u5E38\u7528 API \u7BC4\u4F8B\u3011\n\n\u0027 \u57FA\u672C\u7D50\u69CB\nSub main()\n    Dim swApp As SldWorks.SldWorks\n    Dim swModel As SldWorks.ModelDoc2\n    \n    Set swApp = Application.SldWorks\n    Set swModel = swApp.ActiveDoc\n    \n    If swModel Is Nothing Then\n        MsgBox \u0022\u8ACB\u5148\u6253\u958B\u6587\u6A94\u0022\n        Exit Sub\n    End If\n    \n    \u0027 \u4F60\u7684\u4EE3\u78BC...\nEnd Sub\n\n\u0027 \u5224\u65B7\u6587\u6A94\u985E\u578B\nSelect Case swModel.GetType\n    Case swDocPART: Debug.Print \u0022\u96F6\u4EF6\u0022\n    Case swDocASSEMBLY: Debug.Print \u0022\u88DD\u914D\u9AD4\u0022\n    Case swDocDRAWING: Debug.Print \u0022\u5DE5\u7A0B\u5716\u0022\nEnd Select\n\n\u0027 \u904D\u6B77\u7279\u5FB5\nDim swFeat As SldWorks.Feature\nSet swFeat = swModel.FirstFeature\nDo While Not swFeat Is Nothing\n    Debug.Print swFeat.Name\n    Set swFeat = swFeat.GetNextFeature\nLoop\n\n\u0027 \u904D\u6B77\u88DD\u914D\u9AD4\u7D44\u4EF6\nDim swAssy As SldWorks.AssemblyDoc\nDim vComps As Variant\nSet swAssy = swModel\nvComps = swAssy.GetComponents(True)\nDim i As Long\nFor i = 0 To UBound(vComps)\n    Dim swComp As SldWorks.Component2\n    Set swComp = vComps(i)\n    Debug.Print swComp.Name2\nNext i\n\n\u0027 \u81EA\u5B9A\u7FA9\u5C6C\u6027\nDim swCustPropMgr As SldWorks.CustomPropertyManager\nSet swCustPropMgr = swModel.Extension.CustomPropertyManager(\u0022\u0022)\nswCustPropMgr.Add3 \u0022\u5C6C\u6027\u540D\u0022, swCustomInfoText, \u0022\u503C\u0022, swCustomPropertyAddOption_OnlyIfNew\n\n\u3010\u529F\u80FD\u9700\u6C42\u3011\n[\u5728\u6B64\u63CF\u8FF0\u4F60\u9700\u8981\u7684\u529F\u80FD]",
      "IsDefault": true
    },
    {
      "Id": "7b4223c7-b914-40fe-a2bb-c1d98116423b",
      "Name": "\u6279\u91CF\u8655\u7406\u6587\u4EF6",
      "Content": "\u8ACB\u5E6B\u6211\u751F\u6210\u6279\u91CF\u8655\u7406 SolidWorks \u6587\u4EF6\u7684\u4EE3\u78BC\u3002\r\n\r\n\u3010\u4EFB\u52D9\u63CF\u8FF0\u3011\r\n\u6211\u9700\u8981\u5C0D\u6307\u5B9A\u6587\u4EF6\u593E\u4E2D\u7684\u591A\u500B SolidWorks \u6587\u4EF6\u9032\u884C\u6279\u91CF\u64CD\u4F5C\u3002\r\n\r\n\u3010\u8655\u7406\u8981\u6C42\u3011\r\n- \u6587\u4EF6\u593E\u8DEF\u5F91: [\u8F38\u5165\u8DEF\u5F91\uFF0C\u4F8B\u5982: D:\\Parts]\r\n- \u6587\u4EF6\u985E\u578B: [SLDPRT / SLDASM / SLDDRW / \u5168\u90E8]\r\n- \u662F\u5426\u5305\u542B\u5B50\u6587\u4EF6\u593E: [\u662F/\u5426]\r\n- \u64CD\u4F5C\u5167\u5BB9: [\u63CF\u8FF0\u9700\u8981\u5C0D\u6BCF\u500B\u6587\u4EF6\u57F7\u884C\u7684\u64CD\u4F5C]\r\n\r\n\u3010\u7BC4\u4F8B\u64CD\u4F5C\u3011\r\n1. \u6279\u91CF\u5C0E\u51FA PDF/DWG/STEP\r\n2. \u6279\u91CF\u4FEE\u6539\u81EA\u5B9A\u7FA9\u5C6C\u6027\r\n3. \u6279\u91CF\u91CD\u547D\u540D\u6587\u4EF6\r\n4. \u6279\u91CF\u66F4\u65B0\u5DE5\u7A0B\u5716\r\n5. \u6279\u91CF\u7D71\u8A08\u4FE1\u606F\r\n\r\n\u3010\u8F38\u51FA\u8981\u6C42\u3011\r\n- \u5728\u7D42\u7AEF\u986F\u793A\u8655\u7406\u9032\u5EA6\r\n- \u8A18\u9304\u6210\u529F/\u5931\u6557\u7684\u6587\u4EF6\r\n- \u5B8C\u6210\u5F8C\u986F\u793A\u7D71\u8A08\u6458\u8981",
      "IsDefault": true
    },
    {
      "Id": "41fb7308-b55c-4b98-9cf8-52569b7cdcc8",
      "Name": "\u5C0E\u51FA\u6587\u4EF6\u683C\u5F0F",
      "Content": "\u8ACB\u5E6B\u6211\u751F\u6210 SolidWorks \u6587\u4EF6\u683C\u5F0F\u5C0E\u51FA\u4EE3\u78BC\u3002\r\n\r\n\u3010\u5C0E\u51FA\u8A2D\u7F6E\u3011\r\n- \u6E90\u6587\u4EF6\u985E\u578B: [\u96F6\u4EF6 / \u88DD\u914D\u9AD4 / \u5DE5\u7A0B\u5716]\r\n- \u76EE\u6A19\u683C\u5F0F: [\u9078\u64C7\u683C\u5F0F]\r\n  \u25A1 PDF (\u5DE5\u7A0B\u5716)\r\n  \u25A1 DWG/DXF (\u5DE5\u7A0B\u5716)\r\n  \u25A1 STEP (.step)\r\n  \u25A1 IGES (.igs)\r\n  \u25A1 Parasolid (.x_t)\r\n  \u25A1 STL (3D\u6253\u5370)\r\n  \u25A1 3D PDF\r\n  \u25A1 eDrawings\r\n  \u25A1 \u5716\u7247 (PNG/JPG/BMP)\r\n\r\n- \u4FDD\u5B58\u4F4D\u7F6E: [\u540C\u76EE\u9304 / \u6307\u5B9A\u8DEF\u5F91 / \u76F8\u5C0D\u8DEF\u5F91]\r\n- \u6587\u4EF6\u547D\u540D: [\u76F8\u540C\u540D\u7A31 / \u6DFB\u52A0\u5F8C\u7DB4 / \u81EA\u5B9A\u7FA9\u898F\u5247]\r\n\r\n\u3010\u7279\u6B8A\u9078\u9805\u3011\r\n\u5C0D\u65BC PDF:\r\n- \u7D19\u5F35\u5927\u5C0F: [A4 / A3 / \u81EA\u52D5]\r\n- \u5305\u542B\u6240\u6709\u5716\u7D19: [\u662F/\u5426]\r\n\r\n\u5C0D\u65BC STEP:\r\n- \u7248\u672C: [AP214 / AP203]\r\n\r\n\u5C0D\u65BC STL:\r\n- \u8CEA\u91CF: [\u7CBE\u7D30 / \u6A19\u6E96 / \u7C97\u7CD9]\r\n- \u55AE\u4F4D: [mm / inch]\r\n\r\n\u3010\u5176\u4ED6\u9700\u6C42\u3011\r\n[\u88DC\u5145\u8AAA\u660E]",
      "IsDefault": true
    },
    {
      "Id": "2b7166d0-ba3d-4c0e-b3d2-013c20e2519c",
      "Name": "\u5E7E\u4F55\u64CD\u4F5C",
      "Content": "\u8ACB\u5E6B\u6211\u751F\u6210 SolidWorks \u5E7E\u4F55\u64CD\u4F5C\u4EE3\u78BC\u3002\r\n\r\n\u3010\u64CD\u4F5C\u985E\u578B\u3011\r\n\u25A1 \u7372\u53D6\u9762/\u908A/\u9EDE\u4FE1\u606F\r\n\u25A1 \u8A08\u7B97\u9AD4\u7A4D/\u8868\u9762\u7A4D/\u91CD\u5FC3\r\n\u25A1 \u6E2C\u91CF\u8DDD\u96E2/\u89D2\u5EA6\r\n\u25A1 \u7372\u53D6\u5305\u570D\u76D2\u5C3A\u5BF8\r\n\u25A1 \u67E5\u627E\u6700\u5927/\u6700\u5C0F\u9762\r\n\u25A1 \u904D\u6B77\u62D3\u64B2\u7D50\u69CB\r\n\u25A1 \u5E72\u6D89\u6AA2\u67E5\r\n\u25A1 \u622A\u9762\u5206\u6790\r\n\r\n\u3010\u5E38\u7528\u5E7E\u4F55 API \u7BC4\u4F8B\u3011\r\n\r\n// \u7372\u53D6\u6240\u6709\u9762\r\nIBody2 swBody = ...;\r\nobject[] faces = swBody.GetFaces() as object[];\r\nforeach (IFace2 face in faces)\r\n{\r\n    double area = face.GetArea();\r\n    Print($\u0022\u9762\u7A4D: {area * 1000000:F2} mm\u00B2\u0022);\r\n}\r\n\r\n// \u7372\u53D6\u5305\u570D\u76D2\r\ndouble[] box = swBody.GetBodyBox() as double[];\r\ndouble width = (box[3] - box[0]) * 1000;  // \u8F49\u63DB\u70BA mm\r\ndouble height = (box[4] - box[1]) * 1000;\r\ndouble depth = (box[5] - box[2]) * 1000;\r\n\r\n// \u7372\u53D6\u8CEA\u91CF\u5C6C\u6027\r\nIModelDocExtension ext = swModel.Extension;\r\nIMassProperty massProp = ext.CreateMassProperty();\r\nmassProp.UseSystemUnits = false;\r\ndouble mass = massProp.Mass;\r\ndouble[] cog = massProp.CenterOfMass as double[];\r\n\r\n\u3010\u5177\u9AD4\u9700\u6C42\u3011\r\n[\u63CF\u8FF0\u4F60\u9700\u8981\u7684\u5E7E\u4F55\u64CD\u4F5C]",
      "IsDefault": true
    }
  ],
  "Notes": [],
  "LastOpenedFile": "",
  "WindowWidth": 1934,
  "WindowHeight": 1094,
  "Language": "zh-TW"
}